development:
  adapter: postgresql
  encoding: unicode
  database: sample-app-3-2_development
  host: localhost
  pool: 5
  username: jcaudle
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample-app-3-2_test
  host: localhost
  pool: 5
  username: jcaudle
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sample-app-3-2_production
  pool: 5
  username: jcaudle
  password:
